In [1]:
# Logistic Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Loading & Understanding dataset

In [2]:
# Importing the dataset
dataset = pd.read_csv('data/Social_Network_Ads.csv')

In [3]:
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

## Spliting dataset into training and testing

In [4]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.10, random_state = 0)

In [6]:
X_train[:5, :]

array([[    27,  88000],
       [    41,  52000],
       [    27,  84000],
       [    35,  20000],
       [    43, 112000]])

In [7]:
y_train[:5]

array([0, 0, 0, 0, 1])

## Feature Scaling

In [8]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

In [9]:
sc = StandardScaler()

In [10]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

/Users/swapnilpote/.virtualenvs/py3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [11]:
X_train[:5, :]

array([[-1.05714987,  0.53420426],
       [ 0.2798728 , -0.51764734],
       [-1.05714987,  0.41733186],
       [-0.29313691, -1.45262654],
       [ 0.47087604,  1.23543867]])

In [12]:
y_train[:5]

array([0, 0, 0, 0, 1])

# Logistics Regression

In [13]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression

In [14]:
log = LogisticRegression(random_state = 0)

In [15]:
log.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [16]:
# Predicting the Test set results
y_test_pred = log.predict(X_test)

## Accuracy

In [17]:
# Training accuracy
log.score(X_train, y_train)

0.8361111111111111

In [18]:
# Testing accuracy
log.score(X_train, y_train)

0.8361111111111111

## Confusion Matrix

In [19]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

NameError: name 'y_pred' is not defined

In [ ]:
cm